# Generated by Django 4.2.3 on 2023-07-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_tablerow_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablerow',
            name='emp_id',
            field=models.IntegerField(unique=True),
        ),
    ]
