# Generated by Django 4.2.3 on 2023-07-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Salary', models.CharField(max_length=100)),
                ('DOJ', models.DateField()),
            ],
        ),
    ]
